Repository hack4impact-uiuc/collective-liberty, pull requests merged in 2020-11, with the labels that each got.

#40 📌 Add GET endpoint for arrests data ('/api/arrests')
  api/src/api/arrests.js
  api/src/api/index.js
  api/src/utils/trafficker_arrest_parser.js
  api/src/utils/victim_arrest_parser.js
Labels: P0, backend

#46 🎨 Additional styling
  client/src/components/Map.jsx
  client/src/components/SidebarChart.jsx
  client/src/components/SidebarContainer.jsx
  client/src/pages/MapPage.jsx
  client/src/utils/api.js
  client/src/utils/geocoding.js
Labels: enhancement, frontend

#47 ℹ️ Add Icons to UI
  client/src/components/Map.jsx
  client/src/pages/MapPage.jsx
Labels: enhancement, frontend

#48 🍩 Trafficking scores
  .editorconfig
  .gitattributes
  client/src/components/SidebarContainer.jsx
  client/src/styles/SidebarContainer.css
  client/src/utils/traffickingstatsapi.js
Labels: P0, frontend

#49 🎃 Polygon layer Color-Coordinated by Incidents per State
  .gitignore
  client/src/components/Map.jsx
  client/src/components/StateBoundaries.jsx
  client/src/state_boundaries.json
  client/src/utils/api.js
Labels: P0, frontend
